name: TacoExpress CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore


      - name: Compilar proyecto
        run: dotnet build --no-restore

      - name: Ejecutar pruebas
        run: dotnet test --no-build

      - name: Análisis estático
        run: dotnet format --verify-no-changes
